Hw3.6
Delegant/school pull request #5
Opened 2022-05-06 21:09 UTC by Delegant

2022-05-07 09:14 UTC, OlgaLugacheva requested changes

2022-05-07 09:14 UTC, OlgaLugacheva commented on src/test/java/ru/hogwarts/school/controller/StudentControllerTest.java
> +        shouldReturnStatus200WhenPostTestAvatarPic();
на мой взгляд этому здесь не место, эта секция выполняется перед тестами, получается логика нарушена

2022-05-07 09:14 UTC, OlgaLugacheva commented on src/test/java/ru/hogwarts/school/controller/StudentControllerTest.java
> +        Student responseStudent = restTemplate.postForObject(url, student, Student.class);
зачем мы здесь это повторяем, если есть секция beforeAll  и там все тоже самое?

2022-05-07 09:14 UTC, OlgaLugacheva commented on src/test/java/ru/hogwarts/school/controller/StudentControllerTest.java
> +        Assertions.assertThat(studentId).isNotZero();
это точно работает, потому что мы постим студента с id = 0 ?

2022-05-07 09:14 UTC, OlgaLugacheva commented on src/test/java/ru/hogwarts/school/controller/StudentControllerTest.java
> +        Assertions.assertThat(studentId).isNotZero();
почему мы ожидаем не ноль?

2022-05-08 15:13 UTC, Delegant commented on src/test/java/ru/hogwarts/school/controller/StudentControllerTest.java
> +        shouldReturnStatus200WhenPostTestAvatarPic();
Не понял какая логика нарушена? Так же не понял почему не место?
Для всех тестов нужно добавить студента в базу и потом удалить, поэтому я вынес это в BeforeAll что бы не повторять в каждом тесте. Если не так то как можно иначе?

2022-05-08 15:13 UTC, Delegant commented on src/test/java/ru/hogwarts/school/controller/StudentControllerTest.java
> +        Student responseStudent = restTemplate.postForObject(url, student, Student.class);
В задании сказано, что на каждый эндпоинд нужен тест. Согласен что это избыточно, но ошибка в beforAll в отчет не попадет, поэтому не знал как лучше.

2022-05-08 15:13 UTC, Delegant commented on src/test/java/ru/hogwarts/school/controller/StudentControllerTest.java
> +        Assertions.assertThat(studentId).isNotZero();
Это работает потому что студент поститься с аннотацией GeneratedValue для ID, не узнав под каким ID добавлен студент его не получиться найти текущими эндпоинтами

2022-05-08 16:03 UTC, OlgaLugacheva approved these changes

2022-05-08 16:46 UTC, merged